title:             HairlessCookie
email:             hairlesscookies@gmail.com
description:       Satirical stories, some songs and probably a poem if I'm low enough
author:            HairlessCookie
#url:               "localhost:4000"
url:               "http://hairlesscookie.github.io/"
baseurl:

Social Profiles
github_username:   HairlessCookie
instagram_username: hairlesscookie

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
